    spring.application.name=api-gateway
server.port=8765

#Turned off auto routing by service name (we now use explicit routes)
spring.cloud.gateway.discovery.locator.enabled=false
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/transitops-realm

#---------Routes-----------


#auth-service
#spring.cloud.gateway.routes[0].id=auth-service
#spring.cloud.gateway.routes[0].uri=lb://auth-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1


#vehicle-service
spring.cloud.gateway.routes[1].id=vehicle-service
spring.cloud.gateway.routes[1].uri=lb://vehicle-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/vehicles/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1


#driver-service
spring.cloud.gateway.routes[2].id=driver-service
spring.cloud.gateway.routes[2].uri=lb://driver-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/drivers/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

#trip-service
spring.cloud.gateway.routes[3].id=trip-service
spring.cloud.gateway.routes[3].uri=lb://trip-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/trips/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

#maintenance-service
spring.cloud.gateway.routes[4].id=maintenance-service
spring.cloud.gateway.routes[4].uri=lb://maintenance-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/maintenances/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

#expense-service
spring.cloud.gateway.routes[5].id=expense-service
spring.cloud.gateway.routes[5].uri=lb://expense-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/expenses/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

#report-service (not built yet)
spring.cloud.gateway.routes[0].id=report-service
spring.cloud.gateway.routes[0].uri=lb://report-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/reports/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1



# ------------CORS for the frontend---------------
# two allowed origins
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins[0]=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins[1]=http://localhost:5173
# fix for allowed methods
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[5]=OPTIONS

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders[0]=*